//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int RegistrationPerson { get; set; }
        public int Estatus { get; set; }
        public string Type { get; set; }
    
        public virtual Estatu Estatu { get; set; }
        public virtual Person Person { get; set; }
    }
}
